### ISSUE TITLE
网易云更贴8月1日停止服务

### ISSUE THREAD

**Issue by juzq** [luoyan35714/LessOrMore#10]
真的是悲剧呢，官网已经出公告了，还有什么替代品可以用吗？https://gentie.163.com/index.html

**Comment by luoyan35714** [comment]
打算彻底取消评论系统了。我使用过Disqus，被墙了，使用过多说，关闭了，现在用网易云，也关停了。可供选择的还有畅言，友言，gitment，还有一个韩国的名字忘了。这其中畅言需要域名备案才能用，友言也不是很稳定，韩国那个也存在被墙的潜在风险，gitment存在滥用github的问题。总体来说出路有两个，一个是自己做评论系统，一个是彻底放弃，权衡需求和利弊之后，最终选择放弃评论系统了！

**Comment by luoyan35714** [comment]
详见[http://www.hifreud.com/LessOrMore/2017/07/24/abandon-the-comment-feature/](http://www.hifreud.com/LessOrMore/2017/07/24/abandon-the-comment-feature/)
