### ISSUE TITLE
关于模板的问题

### ISSUE THREAD

**Issue by WangWLab** [luoyan35714/LessOrMore#13]
您好，我在前几天下载了您的模板自己动手改了一下，但是改完之后在文章内部的目录部分会有一些不对的地方，请问可以在哪里修改把那个111去掉呢？
目录是这样的：
![](https://github.com/too-weak/MP3-player-with-C/raw/master/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202017-09-28%20%E4%B8%8B%E5%8D%8810.16.10.png)

**Comment by luoyan35714** [comment]
https://github.com/luoyan35714/LessOrMore/blob/master/_includes/lefttree.html

**Comment by luoyan35714** [comment]
@too-weak 刚发现这个问题，已经修正
