### ISSUE TITLE
配置时的问题

### ISSUE THREAD

**Issue by keyu98** [luoyan35714/LessOrMore#14]
很感谢有这个LessOrMore的模板.
这个revolvermaps地球统计很有意思.
但是改为自己博客后还是要去官网上,获取一个新的地址把以前的替换掉,不然的话,统计的还是原博客的人数.
![screenshot from 2018-08-08 10-24-51](https://user-images.githubusercontent.com/34176272/43812755-5d20ae40-9af5-11e8-8419-21b1f08723c8.png)
获取后就重新开始计数啦
![screenshot from 2018-08-08 10-27-50](https://user-images.githubusercontent.com/34176272/43812843-c0842552-9af5-11e8-8662-f8d0edc8ccfa.png)

**Comment by luoyan35714** [comment]
已经添加了 README 部分，https://github.com/luoyan35714/LessOrMore#%E5%85%B3%E4%BA%8E%E7%BB%9F%E8%AE%A1 挺且修改了下对于统计的应用。
