### ISSUE TITLE
{{site.url}}问题

### ISSUE THREAD

**Issue by Ernie1** [luoyan35714/LessOrMore#20]
_layouts/post.html下
`<a target="_blank" href="{{site.url}}">`
的{{site.url}}指向的并不是_config.yml里的url而是博客的url，需要换名。

**Comment by ZFCC** [comment]
请问这个怎么处理的？是不是和图片展示有关？我的博客现在图片都显示不出了？

**Comment by ZFCC** [comment]
> 
> 
> _layouts/post.html下
> `<a target="_blank" href="{{site.url}}">`
> 的{{site.url}}指向的并不是_config.yml里的url而是博客的url，需要换名。
请问这个怎么处理的？是不是和图片展示有关？我的博客现在图片都显示不出了

**Comment by luoyan35714** [comment]
@Ernie1 想问下是想换成个人简历的URL是么？如果是的话，您可以在您的Fork中进行定制的。
site.url指的是从_config.yml文件中查找url这个参数。

**Comment by Ernie1** [comment]
> @Ernie1 想问下是想换成个人简历的URL是么？如果是的话，您可以在您的Fork中进行定制的。
> site.url指的是从_config.yml文件中查找url这个参数。

您好，我的意思是我的site.url并没有指向_config.yml的url这个参数，而是指向了博客的地址（http://xxx.github.io）。

**Comment by luoyan35714** [comment]
@Ernie1 明白了，是少了一个参数，会在稍后修复！多谢提醒！！再次感谢对LessOrMore的使用和建议！

**Comment by luoyan35714** [comment]
@Ernie1 您好，最近比较忙，没有来得及更新，不过今天重新Review这个Issue的时候发现，此处逻辑是对的。因为
`<a target="_blank" href="{{site.url}}">`
指的是作者的地址，而不是本项目的地址，并且此处是指向了_config.yml的url的地址，并没有指向博客的地址。
