### ISSUE TITLE
scrollspy issue

### ISSUE THREAD

**Issue by eMous** [luoyan35714/LessOrMore#21]
scrollspy method in Bootstrap v3.0.3 has a [bug](https://github.com/twbs/bootstrap/issues/10205) that It doesn't match targets with Chinese id attribute.

And this [Bootstrap](https://netdna.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js) version works well.

**Comment by luoyan35714** [comment]
Hey, man. You are absolutely right! I will fix this issue later and let you know the status.
Besides, another way to avoid the chinese id attribute is using the title as like this:
```bash
诫子书				{#zhugeliang}
------------------------
```

**Comment by zhangshun97** [comment]
> scrollspy method in Bootstrap v3.0.3 has a [bug](https://github.com/twbs/bootstrap/issues/10205) that It doesn't match targets with Chinese id attribute.
> 
> And this [Bootstrap](https://netdna.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js) version works well.

![image](https://user-images.githubusercontent.com/25523760/55384403-3883ec00-555d-11e9-9409-c807c24dff92.png)
This works not so well on my mac... If the second to last title is Chinese, then the problem still occurs.

**Comment by zhangshun97** [comment]
@eMous @luoyan35714 Any ideas? ：）

**Comment by eMous** [comment]
> @eMous @luoyan35714 Any ideas? ：）

Sorry I am not quite familiar with Font-end Web, you may find an solution in StackOverflow. :C
