### ISSUE TITLE
有关图片显示以及其他一些问题

### ISSUE THREAD

**Issue by njuszj** [luoyan35714/LessOrMore#23]
您好，首先非常感谢您提供的这个主题。
我在使用中发现自己博客的图片在手机端浏览时不能完全显示，只能显示左边一部分，虽然可以长按-查看，但还是比较难受，所以过来问问有没有解决方法。
还有一个问题出现在pc端，如果页面不够长，那么在上下滑动页面时左边目录栏会跟着上下移动而错位甚至抖动，不知道是不是我个人设置的问题，如能解答，不甚感激。

**Comment by luoyan35714** [comment]
@njuszj 您好，最近刚换工作比较忙，没来得及查看GITHUB，非常抱歉！
1. 电脑端是通过JS在页面加载完成之后动态调整图片的大小来适配屏幕大小做到的合理显示，但是手机端并没有做，原因是手机端的适配不太好做。给您带来的不便还请谅解！我这边确实没有什么好的办法
2. 这个原因是因为中文锚点的问题导致的，两个方法，第一个是升级Boootstrap的版本，第二个是给每个标题起一个英文的别名
```bash
诫子书				{#zhugeliang}
------------------------
```

**Comment by njuszj** [comment]
非常感谢您的解答！
