### ISSUE TITLE
请教如何顶置一篇文章

### ISSUE THREAD

**Issue by yuzhidi** [luoyan35714/LessOrMore#24]
请教如何顶置一篇文章

**Comment by luoyan35714** [comment]
理论上LessOrMore并没有置顶功能，但是可以通过将文章的时间设置为无限大来实现置顶的功能。

**Comment by zhangshun97** [comment]
一个比较愚蠢但是简单的方式是可以在文章markdown添加一个变量，例如 'top'，然后在显示posts的时候先 for循环一遍把所有带‘top’变量的post显示，再for循环把不带该变量的post显示，这样的好处是同时保证了置顶文章的时间顺序

**Comment by luoyan35714** [comment]
@zhangshun97 您好，我个人挺喜欢这个解决方案的，简单实用。非常感谢给出宝贵的建议

**Comment by luoyan35714** [comment]
@zhangshun97 您好，我个人挺喜欢这个解决方案的，简单实用。非常感谢给出宝贵的建议

**Comment by luoyan35714** [comment]
@yuzhidi 您好，我最近刚换工作比较忙，可能得等下半年才会有时间修改，然后添加置顶功能，给您造成的不便还请谅解！如果您有时间也可以帮忙开发并且合并进来，多谢了！
