### ISSUE TITLE
想问问怎么实现正常显示latex数学公式的功能呢

### ISSUE THREAD

**Issue by bebinca** [luoyan35714/LessOrMore#25]
比如正常显示$x, y\in R^n$这样的表达

**Comment by luoyan35714** [comment]
以下这些插件应该可以帮到你，你看下
mathjax https://www.mathjax.org/
katex https://katex.org/
html to latex http://htmltolatex.sourceforge.net/

**Comment by bebinca** [comment]
感谢感谢！
