### ISSUE TITLE
页面不支持鼠标滚动

### ISSUE THREAD

**Issue by langliu** [luoyan35714/LessOrMore#7]
你好，我在运用这个主题时在我的页面中不支持鼠标滚动，我不知道哪里出了问题

**Comment by luoyan35714** [comment]
不明白你的页面不支持鼠标滚动是什么意思，Demo中是没有这种问题的。请详细阅读Readme文档并重新测试，如果可以重现问题可以及时告诉我。

**Comment by langliu** [comment]
后面没有问题了，谢谢
