### ISSUE TITLE
在使用中有两个疑问，想请教下

### ISSUE THREAD

**Issue by summxu** [luoyan35714/LessOrMore#8]
你好博主。我使用了你的模板，但是我有两个疑问不知道能不能向您请教下：
1.我找不到控制全局的CSS，发现在_post 文章页下面有很大的空白处，我不知道怎么去掉。
![1.png](https://ooo.0o0.ooo/2017/05/25/59268d5e1782e.png)
2.在页面自适应到手机上的时候，发现在 _post 文章页两边有很大的空白间距，我找遍了各个文件的 padding 也没找到在哪去控制，这个控制文件应该在哪？
![2.png](https://ooo.0o0.ooo/2017/05/25/59268d5e17167.png)
您的模板很好 ， 也很美观，我希望能在我以后的博客中根据您的基础改进，谢谢啦！

**Comment by luoyan35714** [comment]
感谢你使用本模板，也非常感谢能够提出宝贵的意见，虽然我不是很认同，哈哈，因为留白其实也是一种美啊。
不过本样式基于开源协议，可以随意扩散修改，你提出的两个问题分别在如下地方进行修改。
1. 修改第一个问题的地方在index.css的6413行.docs-content样式的padding。
2. 修改第二个问题的地方有两个，其中上半部分依旧是6413行.docs-content样式的padding。下半部分是6355行.footer样式的padding和margin。
查找方式可以使用Chrome的F12进入DEBUG工具查找。
希望以上能够帮到你！

**Comment by luoyan35714** [comment]
补充：index.css在目录/styles/css下。
