### ISSUE TITLE
文档写的太差劲了。

### ISSUE THREAD

**Issue by haimawudi** [luoyan35714/LessOrMore#9]
虽然说这个样式还行。本想一用。后来发现这文档，可配置项太少。几乎都定死的。所以我也打算自己重新造轮子了。

**Comment by luoyan35714** [comment]
多谢提出宝贵的意见。本人才疏学浅，做的不足的地方还请见谅！也会在后续根据意见进行修改。BTW，LessOrMore本来就只是一个简单的博客主题，所以配置的越少还是越好的。
